production:
  solr:
    hostname: <%= ENV["SOLR_HOST"] %>
    port:  <%= ENV["SOLR_PORT"] %>
    log_level: WARNING
    path: <%= ENV.fetch("SOLR_PATH", '/solr/development') %>
    read_timeout: 2
    open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST", "localhost") %>
    port:  <%= ENV.fetch("SOLR_PORT", "8982") %>
    log_level: WARNING
    path: <%= ENV.fetch("SOLR_FOLDER", "/solr/test") %>
    read_timeout: 2
    open_timeout: 0.5
